// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJnbykRrjjw5dTLgNHhDi01kG59K40yv0',
    appId: '1:869298080626:web:ec4575e907b50e8c8febeb',
    messagingSenderId: '869298080626',
    projectId: 'auth-tutorial-753f1',
    authDomain: 'auth-tutorial-753f1.firebaseapp.com',
    storageBucket: 'auth-tutorial-753f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgVd5vKQ0UsbgSQtPZcofgnhTqB7z_n0',
    appId: '1:869298080626:android:90d67e5a8e2d16128febeb',
    messagingSenderId: '869298080626',
    projectId: 'auth-tutorial-753f1',
    storageBucket: 'auth-tutorial-753f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG_sohfGpDct_LTbYVRmerISg2GknvQ3s',
    appId: '1:869298080626:ios:5561936330b68cd98febeb',
    messagingSenderId: '869298080626',
    projectId: 'auth-tutorial-753f1',
    storageBucket: 'auth-tutorial-753f1.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG_sohfGpDct_LTbYVRmerISg2GknvQ3s',
    appId: '1:869298080626:ios:5561936330b68cd98febeb',
    messagingSenderId: '869298080626',
    projectId: 'auth-tutorial-753f1',
    storageBucket: 'auth-tutorial-753f1.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJnbykRrjjw5dTLgNHhDi01kG59K40yv0',
    appId: '1:869298080626:web:a8ea0c7a560fa70b8febeb',
    messagingSenderId: '869298080626',
    projectId: 'auth-tutorial-753f1',
    authDomain: 'auth-tutorial-753f1.firebaseapp.com',
    storageBucket: 'auth-tutorial-753f1.firebasestorage.app',
  );

}